app = "laborsubmittal"
[build]
   image ="python:3.9-slim"
[env]
   PORT ="8080"
[[services]]
  internal_port =8080
  protocol = "tcp"
  [[services.ports]]
      port = 80
      handlers =["http"]
      
  [[services.ports]]
      port= 443
      handlers =["tls","http"]

  [[services.tcp_checks]]
     grace_period = "1s"
     interval ="10s"
     timeout= "2s"
     retries = 3

